# Generated by Django 6.0.8 on 2026-08-25 19:25

import django.contrib.postgres.fields
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_job_notifications'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_branching', '0009_changediff_last_updated_auto_now'),
        ('users', '0016_default_ordering_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('branch_name', models.CharField(blank=True, editable=False, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('priority', models.CharField(default='medium', max_length=32)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('auto_merge', models.BooleanField(default=False)),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_request', to='netbox_branching.branch')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'change request',
                'verbose_name_plural': 'change requests',
                'ordering': ('-created',),
                'permissions': (('override_window_changerequest', 'Can merge a change request outside its change window'),),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChangeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('change_label', models.CharField(blank=True, editable=False, max_length=200)),
                ('text', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_comments', to=settings.AUTH_USER_MODEL)),
                ('change_diff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_comments', to='netbox_branching.changediff')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='netbox_change_control.changecomment')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_comments', to='netbox_change_control.changerequest')),
            ],
            options={
                'verbose_name': 'change comment',
                'verbose_name_plural': 'change comments',
                'ordering': ('change_label', 'created', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=1000)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('checks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('object_types', models.ManyToManyField(blank=True, related_name='change_control_policies', to='core.objecttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
                'ordering': ('weight', 'name'),
                'permissions': (('bypass_policy', 'Can write outside a branch while protect_main is enabled'),),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChangeRequestPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('matched', models.BooleanField(default=True)),
                ('matched_object_types', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_bindings', to='netbox_change_control.changerequest')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_bindings', to='netbox_change_control.policy')),
            ],
            options={
                'verbose_name': 'change request policy',
                'verbose_name_plural': 'change request policies',
                'ordering': ('policy__weight', 'policy__name'),
            },
        ),
        migrations.AddField(
            model_name='changerequest',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='change_requests', through='netbox_change_control.ChangeRequestPolicy', to='netbox_change_control.policy'),
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('min_reviews', models.PositiveSmallIntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, related_name='change_control_rules', to='users.group')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='netbox_change_control.policy')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('users', models.ManyToManyField(blank=True, related_name='change_control_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'policy rule',
                'verbose_name_plural': 'policy rules',
                'ordering': ('policy', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('decision', models.CharField(max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('branch_change_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='netbox_change_control.changerequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_control_reviews', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('-created',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MergeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('required', models.BooleanField(default=True)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('details_url', models.URLField(blank=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='netbox_change_control.changerequest')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'merge check',
                'verbose_name_plural': 'merge checks',
                'ordering': ('change_request', 'name'),
                'constraints': [models.UniqueConstraint(fields=('change_request', 'name'), name='netbox_change_control_mergecheck_unique_request_check')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='changerequestpolicy',
            constraint=models.UniqueConstraint(fields=('change_request', 'policy'), name='netbox_change_control_changerequestpolicy_unique_request_policy'),
        ),
        migrations.AddConstraint(
            model_name='policyrule',
            constraint=models.UniqueConstraint(fields=('policy', 'name'), name='netbox_change_control_policyrule_unique_policy_name'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('change_request', 'reviewer'), name='netbox_change_control_review_unique_request_reviewer'),
        ),
    ]
