# Generated by Django 6.0.8 on 2026-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_change_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='condition_state',
            field=models.CharField(default='either', max_length=16),
        ),
    ]
