# Generated by Django 6.0.8 on 2026-08-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_change_control', '0002_policy_condition_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
