# Generated by Django 6.0.8 on 2026-08-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_change_control', '0003_changerequest_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ('-created',), 'permissions': (('override_window_changerequest', 'Can merge a change request outside its change window'), ('abandon_changerequest', 'Can abandon a change request'), ('reopen_changerequest', 'Can reopen an abandoned change request'))},
        ),
    ]
