# Generated by Django 6.0.8 on 2026-08-31 14:11

from django.db import migrations, models


def populate_cached_state(apps, schema_editor):
    """
    Fill the new columns for change requests that already exist.

    Without this an upgraded install shows every open request as conflict-free and not ready
    until something happens to refresh it, which is worse than showing nothing: the columns
    would be confidently wrong.

    Only the conflict half is computed. It reads ChangeDiff and the branch's unsynced changes,
    both of which live in the main schema, so it is safe here. Readiness needs the policy
    evaluation, which reaches into each branch's own schema, and a migration is the wrong
    place to go looking for those; it is left at the default and corrects itself the first
    time anything touches the request.
    """
    ChangeRequest = apps.get_model('netbox_change_control', 'ChangeRequest')

    try:
        from netbox_change_control.conflicts import conflicting_diffs
    except Exception:
        return

    for change_request in ChangeRequest.objects.filter(branch__isnull=False).select_related('branch'):
        try:
            conflicted = bool(conflicting_diffs(change_request.branch))
        except Exception:
            # A branch whose schema has gone, or any other surprise, must not stop the upgrade.
            continue
        if conflicted:
            ChangeRequest.objects.filter(pk=change_request.pk).update(cached_conflicted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_change_control', '0004_alter_changerequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='cached_conflicted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='cached_gates_cleared',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(populate_cached_state, migrations.RunPython.noop),
    ]
