# Generated by Django 6.0.8 on 2026-08-31 14:11

from django.db import migrations, models


def populate_cached_state(apps, schema_editor):
    """
    Fill the new columns for change requests that already exist.

    Without this an upgraded install shows every open request as conflict-free until something
    happens to refresh it, which is worse than showing nothing: the column would be
    confidently wrong.

    The **live** Branch model is used deliberately. A migration is normally handed historical
    models, but those carry fields only and no methods, and working out whether a conflict is
    real needs `Branch.get_unsynced_changes()`. Reading it from the historical model silently
    did nothing at all, which is the failure this comment exists to prevent repeating.

    Only the conflict half is filled. It reads ChangeDiff and the branch's unsynced changes,
    both in the main schema, so it is safe here. Readiness needs the policy evaluation, which
    reaches into each branch's own schema; a migration is the wrong place to go looking for
    those, so it is left at the default and corrects itself the first time anything touches
    the request.
    """
    ChangeRequest = apps.get_model('netbox_change_control', 'ChangeRequest')

    try:
        from netbox_branching.models import Branch
        from netbox_change_control.conflicts import conflicting_diffs
    except Exception:
        return

    branches = {b.pk: b for b in Branch.objects.all()}
    conflicted = []
    for pk, branch_id in ChangeRequest.objects.filter(branch__isnull=False).values_list('pk', 'branch_id'):
        branch = branches.get(branch_id)
        if branch is None:
            continue
        try:
            if conflicting_diffs(branch):
                conflicted.append(pk)
        except Exception:
            # A branch whose schema has gone, or any other surprise, must not stop an upgrade.
            continue

    if conflicted:
        ChangeRequest.objects.filter(pk__in=conflicted).update(cached_conflicted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_change_control', '0004_alter_changerequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='cached_conflicted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='cached_gates_cleared',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(populate_cached_state, migrations.RunPython.noop),
    ]
