# Generated by Django 6.0.8 on 2026-08-31 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_change_control', '0005_changerequest_cached_conflicted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequestpolicy',
            name='created',
        ),
        migrations.RemoveField(
            model_name='changerequestpolicy',
            name='matched',
        ),
    ]
